version: "3.8"

services:
  asking-card:
    image: lynchz/asking-p-bas:latest
    container_name: asking-card
    ports:
      - "3004:3000"
      - "3005:3001"
    environment:
      - DISCORD_WEBHOOK_URL=your_webhook_url_here
      - DISCORD_NOTIFICATIONS_ENABLED=true
      - NEXT_PUBLIC_SOCKET_URL=https://asking.lynchz.dev:3005
      - NODE_ENV=production
    restart: unless-stopped
